### ISSUE TITLE
Lista de Atividades

### ISSUE THREAD

**Issue by IgorAssuncao** [IgorAssuncao/PB_Infra_Architecture_Python#6]
### Lista que contém todas as atividades

- [x] [#1 Setar python virtualenv em todos os ambientes](https://github.com/IgorAssuncao/PB_Arq_Infnet/projects/1#card-18202831)
- [x] [#3 Desenvolvimento do Cliente](https://github.com/IgorAssuncao/PB_Arq_Infnet/projects/1#card-18204476)
- [x] [#4 Desenvolvimento do Servidor](https://github.com/IgorAssuncao/PB_Arq_Infnet/projects/1#card-18204478)
- [x] [#5 Implementação que realize conexão entre cliente e servidor](https://github.com/IgorAssuncao/PB_Arq_Infnet/projects/1#card-18204484)
- [x] [#7 Desenvolvimento de função (ou funções) para recolher informações do disco do lado do servidor](https://github.com/IgorAssuncao/PB_Arq_Infnet/projects/1#card-18204450)
- [x] [#8 Desenvolvimento de função (ou funções) para recolher informações da rede do lado do servidor](https://github.com/IgorAssuncao/PB_Arq_Infnet/projects/1#card-18204445)
- [x] [#9 Desenvolvimento de função (ou funções) para recolher informações da memória do lado do servidor](https://github.com/IgorAssuncao/PB_Arq_Infnet/projects/1#card-18204443)
- [x] [#10 Desenvolvimento de função (ou funções) para recolher informações da cpu do lado do servidor](https://github.com/IgorAssuncao/PB_Arq_Infnet/projects/1#card-18204438)
